<?php

return [
    'categories' => ['Skin Care', 'Hair Care', 'Makeup', 'Perfume', 'Body'],

    'products' => [
        [
            'id' => 1,
            'slug' => 'the-ordinary-niacinamide-10-zinc-1',
            'name' => 'The Ordinary Niacinamide 10% + Zinc 1%',
            'brand' => 'The Ordinary',
            'category' => 'Skin Care',
            'price' => 7.90,
            'sale_price' => 6.90,
            'product_type' => 'Serum',
            'properties' => ['Oil Control', 'Brightening'],
            'gender' => 'Unisex',
            'size' => '30ml',
            'images' => [
                'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1601049676869-702ea24cfd58?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=85',
            ],
            'description' => 'A lightweight serum focused on visible clarity, oil balance, and a smoother-looking skin texture.',
        ],
        [
            'id' => 2,
            'slug' => 'olaplex-no-3-hair-perfector',
            'name' => 'Olaplex No.3 Hair Perfector',
            'brand' => 'Olaplex',
            'category' => 'Hair Care',
            'price' => 29,
            'sale_price' => null,
            'product_type' => 'Hair Mask',
            'properties' => ['Anti-Aging', 'Hydrating'],
            'gender' => 'Unisex',
            'size' => '100ml',
            'images' => [
                'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&w=900&q=85',
            ],
            'description' => 'A pre-shampoo treatment for damaged hair routines and a polished, healthy-looking finish.',
        ],
        [
            'id' => 3,
            'slug' => 'charlotte-tilbury-pillow-talk-matte-revolution-lipstick',
            'name' => 'Charlotte Tilbury Pillow Talk Matte Revolution Lipstick',
            'brand' => 'Charlotte Tilbury',
            'category' => 'Makeup',
            'price' => 34,
            'sale_price' => 29,
            'product_type' => 'Lipstick',
            'properties' => ['Long Lasting'],
            'gender' => 'Women',
            'size' => '30ml',
            'images' => [
                'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=85',
            ],
            'description' => 'A soft matte lipstick in a signature nude-pink shade for elegant everyday makeup.',
        ],
        [
            'id' => 4,
            'slug' => 'dior-jadore-eau-de-parfum',
            'name' => "Dior J'adore Eau de Parfum",
            'brand' => 'Dior',
            'category' => 'Perfume',
            'price' => 96,
            'sale_price' => null,
            'product_type' => 'Eau de Parfum',
            'properties' => ['Long Lasting'],
            'gender' => 'Women',
            'size' => '100ml',
            'images' => [
                'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=900&q=85',
            ],
            'description' => 'A luminous floral fragrance profile made for a refined signature scent wardrobe.',
        ],
        [
            'id' => 5,
            'slug' => 'sol-de-janeiro-brazilian-bum-bum-cream',
            'name' => 'Sol de Janeiro Brazilian Bum Bum Cream',
            'brand' => 'Sol de Janeiro',
            'category' => 'Body',
            'price' => 48,
            'sale_price' => null,
            'product_type' => 'Moisturizer',
            'properties' => ['Hydrating'],
            'gender' => 'Women',
            'size' => '200ml',
            'images' => [
                'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=900&q=85',
            ],
            'description' => 'A rich body cream with a smooth texture for daily body care and a warm beauty ritual.',
        ],
        [
            'id' => 6,
            'slug' => 'cerave-moisturising-cream',
            'name' => 'CeraVe Moisturising Cream',
            'brand' => 'CeraVe',
            'category' => 'Skin Care',
            'price' => 17,
            'sale_price' => 14,
            'product_type' => 'Moisturizer',
            'properties' => ['Hydrating', 'Sensitive Skin'],
            'gender' => 'Unisex',
            'size' => '200ml',
            'images' => [
                'https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=900&q=85',
            ],
            'description' => 'A classic face and body moisturising cream for simple, barrier-focused daily care.',
        ],
        [
            'id' => 7,
            'slug' => 'la-roche-posay-anthelios-uvmune-400-invisible-fluid-spf50',
            'name' => 'La Roche-Posay Anthelios UVMune 400 Invisible Fluid SPF50+',
            'brand' => 'La Roche-Posay',
            'category' => 'Skin Care',
            'price' => 22,
            'sale_price' => null,
            'product_type' => 'Moisturizer',
            'properties' => ['Sensitive Skin', 'Oil Control'],
            'gender' => 'Unisex',
            'size' => '50ml',
            'images' => [
                'https://images.unsplash.com/photo-1601049676869-702ea24cfd58?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=900&q=85',
            ],
            'description' => 'A lightweight sunscreen fluid for everyday protection and smooth makeup prep.',
        ],
        [
            'id' => 8,
            'slug' => 'fenty-beauty-gloss-bomb-universal-lip-luminizer',
            'name' => 'Fenty Beauty Gloss Bomb Universal Lip Luminizer',
            'brand' => 'Fenty Beauty',
            'category' => 'Makeup',
            'price' => 24,
            'sale_price' => 19,
            'product_type' => 'Lipstick',
            'properties' => ['Hydrating', 'Long Lasting'],
            'gender' => 'Women',
            'size' => '30ml',
            'images' => [
                'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=900&q=85',
            ],
            'description' => 'A high-shine lip gloss designed for a plush finish and easy everyday wear.',
        ],
        [
            'id' => 9,
            'slug' => 'rare-beauty-soft-pinch-liquid-blush',
            'name' => 'Rare Beauty Soft Pinch Liquid Blush',
            'brand' => 'Rare Beauty',
            'category' => 'Makeup',
            'price' => 26,
            'sale_price' => null,
            'product_type' => 'Blush',
            'properties' => ['Long Lasting', 'Brightening'],
            'gender' => 'Women',
            'size' => '30ml',
            'images' => [
                'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=85',
            ],
            'description' => 'A liquid blush with buildable color for a fresh, softly radiant makeup look.',
        ],
        [
            'id' => 10,
            'slug' => 'ysl-beauty-libre-eau-de-parfum',
            'name' => 'YSL Beauty Libre Eau de Parfum',
            'brand' => 'YSL Beauty',
            'category' => 'Perfume',
            'price' => 105,
            'sale_price' => 89,
            'product_type' => 'Eau de Parfum',
            'properties' => ['Long Lasting'],
            'gender' => 'Unisex',
            'size' => '100ml',
            'images' => [
                'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=85',
                'https://images.unsplash.com/photo-1588405748880-12d1d2a59d32?auto=format&fit=crop&w=900&q=85',
            ],
            'description' => 'A warm floral fragrance with a confident, elegant evening-ready character.',
        ],
    ],
];
